// Code generated by 'ddd-gen domain', DO NOT EDIT.
package domain

import account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/Account"

// Facts returns collected domain facts
// implements application layer's FactKeeper interface.
func (mna *MakeNewAccount) Facts() []interface{} {
	return mna.facts
}

// Errors returns collected domain errors
// implements application layer's ErrorKeeper interface.
func (mna *MakeNewAccount) Errors() []error {
	return mna.errors
}

// raise records domain errors
func (mna *MakeNewAccount) raise(err error) {
	mna.errors = append(mna.errors, err)
}

// recordOn records facts and applies them to the domain
func (mna *MakeNewAccount) recordOn(a *account.Account, fact interface{}) {
	a.Apply(fact)
	mna.facts = append(mna.facts, fact)
}
