// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	policy "github.com/xoe-labs/ddd-gen/internal/test-svc/app/policy"
	repository "github.com/xoe-labs/ddd-gen/internal/test-svc/app/repository"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Account ===
*/

// BlockAccount represents a BlockAccount command
type BlockAccount struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs BlockAccount
func (ba *BlockAccount) handle(ctx context.Context, a *account.Account) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

// Identifier returns the identifier of the object on which to perform BlockAccount
func (ba BlockAccount) Identifier() gouuid.UUID {
	return ba.uuid
}

// Assert that BlockAccount implements Identifiable interface!
var _ repository.Identifiable = (*BlockAccount)(nil)

/*
	=> Policeable interface implementation ...
*/

// User returns the identifier of the caller
func (ba BlockAccount) User() string {
	return ba.userId
}

// ElevationToken returns an elevation token in posession of the caller
func (ba BlockAccount) ElevationToken() string {
	return ba.elevationToken
}

// Assert that BlockAccount implements Policeable interface!
var _ policy.Policeable = (*BlockAccount)(nil)
