// Code generated by 'ddd-gen app command': DO NOT EDIT.

package command

import (
	"context"
	errwrap "github.com/hashicorp/errwrap"
	app "github.com/xoe-labs/ddd-gen/internal/test-svc/app"
	errors "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors"
	domain "github.com/xoe-labs/ddd-gen/internal/test-svc/domain"
	"reflect"
)

// Topic: Account

var (
	// ErrNotAuthorizedToBlockAccount signals that the caller is not authorized to perform BlockAccount
	ErrNotAuthorizedToBlockAccount = errors.NewAuthorizationError("ErrNotAuthorizedToBlockAccount")
	// ErrBlockAccountHasNoTarget signals that BlockAccount's target was not distinguishable
	ErrBlockAccountHasNoTarget = errors.NewTargetIdentificationError("ErrBlockAccountHasNoTarget")
	// ErrBlockAccountLoadingFailed signals that BlockAccount storage failed to load the entity
	ErrBlockAccountLoadingFailed = errors.NewStorageLoadingError("ErrBlockAccountLoadingFailed")
	// ErrBlockAccountSavingFailed signals that BlockAccount failed to save the entity
	ErrBlockAccountSavingFailed = errors.NewStorageSavingError("ErrBlockAccountSavingFailed")
	// ErrBlockAccountFailedInDomain signals that BlockAccount failed in the domain layer
	ErrBlockAccountFailedInDomain = errors.NewDomainError("ErrBlockAccountFailedInDomain")
)

// BlockAccountHandlerWrapper knows how to perform BlockAccount
type BlockAccountHandlerWrapper struct {
	rw app.RequiresStorageWriterReader
	p  app.RequiresPolicer
}

// NewBlockAccountHandlerWrapper returns BlockAccountHandlerWrapper
func NewBlockAccountHandlerWrapper(rw app.RequiresStorageWriterReader, p app.RequiresPolicer) *BlockAccountHandlerWrapper {
	if reflect.ValueOf(rw).IsZero() {
		panic("no 'rw' provided!")
	}
	if reflect.ValueOf(p).IsZero() {
		panic("no 'p' provided!")
	}
	return &BlockAccountHandlerWrapper{rw: rw, p: p}
}

// Handle generically performs BlockAccount
func (h BlockAccountHandlerWrapper) Handle(ctx context.Context, ba domain.BlockAccount, actor app.OffersPoliceable, target app.OffersDistinguishable) error {
	// assert that target is distinguishable
	if !target.IsDistinguishable() {
		return ErrBlockAccountHasNoTarget
	}
	// load entity from store; handle + wrap error
	a, loadErr := h.rw.Load(ctx, target)
	if loadErr != nil {
		return errwrap.Wrap(ErrBlockAccountLoadingFailed, loadErr)
	}
	// assert authorization via policy interface
	if ok := h.p.Can(ctx, actor, "BlockAccount", a); !ok {
		// return opaque error: handle potentially sensitive policy errors out-of-band!
		return ErrNotAuthorizedToBlockAccount
	}
	// assert correct command handling by the domain
	if ok := ba.Handle(ctx, a); !ok {
		var domErr error
		for i, e := range ba.Errors() {
			if i == 0 {
				domErr = e
			} else {
				domErr = errwrap.Wrap(domErr, e)
			}
		}
		return ErrBlockAccountFailedInDomain
	}
	// save domain facts to storage
	saveErr := h.rw.SaveFacts(ctx, target, app.OffersFactKeeper(&ba))
	if saveErr != nil {
		return errwrap.Wrap(ErrBlockAccountSavingFailed, saveErr)
	}
	return nil
}

// compile time assertions
var (
	_ app.RequiresCommandHandler = (*domain.BlockAccount)(nil)
	_ app.RequiresErrorKeeper    = (*domain.BlockAccount)(nil)
	_ app.OffersFactKeeper       = (*domain.BlockAccount)(nil)
)
