// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	policy "github.com/xoe-labs/ddd-gen/internal/test-svc/app/policy"
	repository "github.com/xoe-labs/ddd-gen/internal/test-svc/app/repository"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Account ===
*/

// DeleteAccount represents a DeleteAccount command
type DeleteAccount struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs DeleteAccount
func (da *DeleteAccount) handle(ctx context.Context, a *account.Account) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

// Identifier returns the identifier of the object on which to perform DeleteAccount
func (da DeleteAccount) Identifier() gouuid.UUID {
	return da.uuid
}

// Assert that DeleteAccount implements Identifiable interface!
var _ repository.Identifiable = (*DeleteAccount)(nil)

/*
	=> Policeable interface implementation ...
*/

// User returns the identifier of the caller
func (da DeleteAccount) User() string {
	return da.userId
}

// ElevationToken returns an elevation token in posession of the caller
func (da DeleteAccount) ElevationToken() string {
	return da.elevationToken
}

// Assert that DeleteAccount implements Policeable interface!
var _ policy.Policeable = (*DeleteAccount)(nil)
