// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	policy "github.com/xoe-labs/ddd-gen/internal/test-svc/app/policy"
	repository "github.com/xoe-labs/ddd-gen/internal/test-svc/app/repository"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Balance ===
*/

// IncreaseBalance represents a IncreaseBalance command
type IncreaseBalance struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs IncreaseBalance
func (ib *IncreaseBalance) handle(ctx context.Context, a *account.Account) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

// Identifier returns the identifier of the object on which to perform IncreaseBalance
func (ib IncreaseBalance) Identifier() gouuid.UUID {
	return ib.uuid
}

// Assert that IncreaseBalance implements Identifiable interface!
var _ repository.Identifiable = (*IncreaseBalance)(nil)

/*
	=> Policeable interface implementation ...
*/

// User returns the identifier of the caller
func (ib IncreaseBalance) User() string {
	return ib.userId
}

// ElevationToken returns an elevation token in posession of the caller
func (ib IncreaseBalance) ElevationToken() string {
	return ib.elevationToken
}

// Assert that IncreaseBalance implements Policeable interface!
var _ policy.Policeable = (*IncreaseBalance)(nil)
