// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	balancer "github.com/xoe-labs/ddd-gen/internal/test-svc/app/balancer"
	policy "github.com/xoe-labs/ddd-gen/internal/test-svc/app/policy"
	repository "github.com/xoe-labs/ddd-gen/internal/test-svc/app/repository"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Balance ===
*/

// IncreaseBalanceFromSvc represents a IncreaseBalanceFromSvc command
type IncreaseBalanceFromSvc struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs IncreaseBalanceFromSvc
func (ibfs *IncreaseBalanceFromSvc) handle(ctx context.Context, a *account.Account, svc *balancer.Balancer) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

// Identifier returns the identifier of the object on which to perform IncreaseBalanceFromSvc
func (ibfs IncreaseBalanceFromSvc) Identifier() gouuid.UUID {
	return ibfs.uuid
}

// Assert that IncreaseBalanceFromSvc implements Identifiable interface!
var _ repository.Identifiable = (*IncreaseBalanceFromSvc)(nil)

/*
	=> Policeable interface implementation ...
*/

// User returns the identifier of the caller
func (ibfs IncreaseBalanceFromSvc) User() string {
	return ibfs.userId
}

// ElevationToken returns an elevation token in posession of the caller
func (ibfs IncreaseBalanceFromSvc) ElevationToken() string {
	return ibfs.elevationToken
}

// Assert that IncreaseBalanceFromSvc implements Policeable interface!
var _ policy.Policeable = (*IncreaseBalanceFromSvc)(nil)
