// Code generated by 'ddd-gen app command': DO NOT EDIT.

package command

import (
	"context"
	errwrap "github.com/hashicorp/errwrap"
	app "github.com/xoe-labs/ddd-gen/internal/test-svc/app"
	errors "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors"
	domain "github.com/xoe-labs/ddd-gen/internal/test-svc/domain"
	"reflect"
)

// Topic: Balance

var (
	// ErrNotAuthorizedToIncreaseBalance signals that the caller is not authorized to perform IncreaseBalance
	ErrNotAuthorizedToIncreaseBalance = errors.NewAuthorizationError("ErrNotAuthorizedToIncreaseBalance")
	// ErrIncreaseBalanceHasNoTarget signals that IncreaseBalance's target was not distinguishable
	ErrIncreaseBalanceHasNoTarget = errors.NewTargetIdentificationError("ErrIncreaseBalanceHasNoTarget")
	// ErrIncreaseBalanceLoadingFailed signals that IncreaseBalance storage failed to load the entity
	ErrIncreaseBalanceLoadingFailed = errors.NewStorageLoadingError("ErrIncreaseBalanceLoadingFailed")
	// ErrIncreaseBalanceSavingFailed signals that IncreaseBalance failed to save the entity
	ErrIncreaseBalanceSavingFailed = errors.NewStorageSavingError("ErrIncreaseBalanceSavingFailed")
	// ErrIncreaseBalanceFailedInDomain signals that IncreaseBalance failed in the domain layer
	ErrIncreaseBalanceFailedInDomain = errors.NewDomainError("ErrIncreaseBalanceFailedInDomain")
)

// IncreaseBalanceHandlerWrapper knows how to perform IncreaseBalance
type IncreaseBalanceHandlerWrapper struct {
	rw app.RequiresStorageWriterReader
	p  app.RequiresPolicer
}

// NewIncreaseBalanceHandlerWrapper returns IncreaseBalanceHandlerWrapper
func NewIncreaseBalanceHandlerWrapper(rw app.RequiresStorageWriterReader, p app.RequiresPolicer) *IncreaseBalanceHandlerWrapper {
	if reflect.ValueOf(rw).IsZero() {
		panic("no 'rw' provided!")
	}
	if reflect.ValueOf(p).IsZero() {
		panic("no 'p' provided!")
	}
	return &IncreaseBalanceHandlerWrapper{rw: rw, p: p}
}

// Handle generically performs IncreaseBalance
func (h IncreaseBalanceHandlerWrapper) Handle(ctx context.Context, ib domain.IncreaseBalance, actor app.OffersPoliceable, target app.OffersDistinguishable) error {
	// assert that target is distinguishable
	if !target.IsDistinguishable() {
		return ErrIncreaseBalanceHasNoTarget
	}
	// load entity from store; handle + wrap error
	a, loadErr := h.rw.Load(ctx, target)
	if loadErr != nil {
		return errwrap.Wrap(ErrIncreaseBalanceLoadingFailed, loadErr)
	}
	// assert authorization via policy interface
	if ok := h.p.Can(ctx, actor, "IncreaseBalance", a); !ok {
		// return opaque error: handle potentially sensitive policy errors out-of-band!
		return ErrNotAuthorizedToIncreaseBalance
	}
	// assert correct command handling by the domain
	if ok := ib.Handle(ctx, a); !ok {
		var domErr error
		for i, e := range ib.Errors() {
			if i == 0 {
				domErr = e
			} else {
				domErr = errwrap.Wrap(domErr, e)
			}
		}
		return ErrIncreaseBalanceFailedInDomain
	}
	// save domain facts to storage
	saveErr := h.rw.SaveFacts(ctx, target, app.OffersFactKeeper(&ib))
	if saveErr != nil {
		return errwrap.Wrap(ErrIncreaseBalanceSavingFailed, saveErr)
	}
	return nil
}

// compile time assertions
var (
	_ app.RequiresCommandHandler = (*domain.IncreaseBalance)(nil)
	_ app.RequiresErrorKeeper    = (*domain.IncreaseBalance)(nil)
	_ app.OffersFactKeeper       = (*domain.IncreaseBalance)(nil)
)
