// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	policy "github.com/xoe-labs/ddd-gen/internal/test-svc/app/policy"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Account ===
*/

// MakeNewAccountWithOutId represents a MakeNewAccountWithOutId command
type MakeNewAccountWithOutId struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs MakeNewAccountWithOutId
func (mnawoi *MakeNewAccountWithOutId) handle(ctx context.Context, a *account.Account) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

/*
	=> Policeable interface implementation ...
*/

// User returns the identifier of the caller
func (mnawoi MakeNewAccountWithOutId) User() string {
	return mnawoi.userId
}

// ElevationToken returns an elevation token in posession of the caller
func (mnawoi MakeNewAccountWithOutId) ElevationToken() string {
	return mnawoi.elevationToken
}

// Assert that MakeNewAccountWithOutId implements Policeable interface!
var _ policy.Policeable = (*MakeNewAccountWithOutId)(nil)
