// Code generated by 'ddd-gen app command': THESE ARE STUBS, PLEASE EDIT.

package command

import (
	"context"
	gouuid "github.com/satori/go.uuid"
	repository "github.com/xoe-labs/ddd-gen/internal/test-svc/app/repository"
	account "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/account"
)

/*
	=== Topic: Holder ===
*/

// ValidateHolder represents a ValidateHolder command
type ValidateHolder struct {
	uuid           gouuid.UUID
	userId         string
	elevationToken string

	// TODO: design command event/message fields (evtl. use protobuf + protoc-gen-go)
}

// handle specifically performs ValidateHolder
func (vh *ValidateHolder) handle(ctx context.Context, a *account.Account) error {
	// TODO: implement app logic
	return nil
}

/*
	=> Identifiable interface implementation ...
*/

// Identifier returns the identifier of the object on which to perform ValidateHolder
func (vh ValidateHolder) Identifier() gouuid.UUID {
	return vh.uuid
}

// Assert that ValidateHolder implements Identifiable interface!
var _ repository.Identifiable = (*ValidateHolder)(nil)
