// Code generated by 'ddd-gen domain entity', DO NOT EDIT.
package account

import (
	"errors"
	"fmt"
	distinguishable "github.com/xoe-labs/ddd-gen/internal/test-svc/app/distinguishable"
	holder "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/holder"
	"reflect"
)

// Constructors ...

// New returns a guaranteed-to-be-valid Account or an error
func New(holder holder.Holder, altHolders map[distinguishable.Target]holder.Holder, holderRoles map[holder.Holder]string, address string) (*Account, error) {
	if reflect.ValueOf(holder).IsZero() {
		return nil, errors.New("field holder is empty")
	}
	if reflect.ValueOf(altHolders).IsZero() {
		return nil, errors.New("field alternative holders is empty")
	}
	if reflect.ValueOf(holderRoles).IsZero() {
		return nil, errors.New("field holder role map is empty")
	}
	a := &Account{
		address:     address,
		altHolders:  altHolders,
		holder:      holder,
		holderRoles: holderRoles,
	}
	return a, nil
}

// MustNew returns a guaranteed-to-be-valid Account or panics
func MustNew(holder holder.Holder, altHolders map[distinguishable.Target]holder.Holder, holderRoles map[holder.Holder]string, address string) *Account {
	a, err := New(holder, altHolders, holderRoles, address)
	if err != nil {
		panic(err)
	}
	return a
}

// Marshalers ...

// UnmarshalFromStore unmarshals Account from the repository so that non-constructable
// private fields can still be initialized from (private) repository state
//
// Important: DO NEVER USE THIS METHOD EXCEPT FROM THE REPOSITORY
// Reason: This method initializes private state, so you could corrupt the domain.
func UnmarshalFromStore(holder holder.Holder, altHolders map[distinguishable.Target]holder.Holder, holderRoles map[holder.Holder]string, address string, balance int64, movements []int64, blocked bool, blockReason bool, unblockReason bool, archived bool, archivedReason bool, validHolder bool, validatedBy string) *Account {
	a := MustNew(holder, altHolders, holderRoles, address)
	a.balance = balance
	a.movements = movements
	a.blocked = blocked
	a.blockReason = blockReason
	a.unblockReason = unblockReason
	a.archived = archived
	a.archivedReason = archivedReason
	a.validHolder = validHolder
	a.validatedBy = validatedBy
	return a
}

// Accessors ...

// Holder returns holder value
func (a *Account) Holder() holder.Holder {
	return a.holder
}

// SetAltHolders sets altHolders value
func (a *Account) SetAltHolders(altHolders map[distinguishable.Target]holder.Holder) {
	a.altHolders = altHolders
}

// Utilities ...

// Equal answers whether v is equivalent to a
// Always returns false if v is not a Account
func (a Account) Equal(v interface{}) bool {
	other, ok := v.(Account)
	if !ok {
		return false
	}
	return true
}

// String implements the fmt.Stringer interface and returns the native format of Account
func (a Account) String() string {
	return fmt.Sprintf("")
}
