// Copyright © 2020 David Arnold <dar@xoe.solutions>
// SPDX-License-Identifier: MIT

package gen_domain

import (
	"github.com/dave/jennifer/jen"

	"github.com/xoe-labs/ddd-gen/pkg/gen_domain/generator"
)

func generateCommandHelperMethods(f *jen.File, typ string, entity generator.QualId) {

	// Add a package comment, so IDEs detect files as generated
	f.PackageComment("Code generated by 'ddd-gen domain', DO NOT EDIT.")

	_ = generator.GenFuncFacts(f, typ)
	_ = generator.GenFuncErrors(f, typ)
	_ = generator.GenFuncraise(f, typ)
	_ = generator.GenFuncrecordOn(f, typ, entity)
}

func generateCommandHandleStub(f *jen.File, typ string, entity generator.QualId) {
	_ = generator.GenFuncHandleStub(f, typ, entity)
}
