domain:                       "github.com/xoe-labs/ddd-gen/internal/test-svc/domain"
entity:                       "github.com/xoe-labs/ddd-gen/internal/test-svc/domain/Account.Account"
# Error Contructors
authorizationErrorNew:        "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors.NewAuthorizationError"
targetIdentificationErrorNew: "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors.NewTargetIdentificationError"
storageLoadingErrorNew:       "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors.NewStorageLoadingError"
storageSavingErrorNew:        "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors.NewStorageSavingError"
domainErrorNew:               "github.com/xoe-labs/ddd-gen/internal/test-svc/app/errors.NewDomainError"
