/*
Copyright © 2020 David Arnold <dar@xoe.solutions>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"github.com/spf13/cobra"
	"github.com/xoe-labs/ddd-gen/pkg/gen_domain"
)

var (
	validatorMethod string
)

// domainEntityCmd represents the entity command
var domainEntityCmd = &cobra.Command{
	Use:   "entity",
	Short: "Generates idiomatic go code for an entity within the domain layer",
	Long: `Generates idiomatic go code for an entity based on struct field tags.

  Available Annotations:
    Key "entity" | Separator: ";"
      private             - this is private state, it can only be initialized directly from the repository
      required,error msg  - if not present in the constructor, an error with the provided message will be returned
      getter              - generates a simple getter for this field
      setter              - generates a simple setter for this field
      stringer            - generates a stringer for this field
      equal[,reflect]     - incorporates this field into the equality tester method, with reflect option: use reflect.DeepEqual

  Expected Folder Structure:
    ./domain
    ├── livecall
    │   ├── livecall.go
    │   └── livecall_gen.go // generated by this tool
    ├── party
    │   ├── party.go
    │   └── party_gen.go // generated by this tool
    └── ...`,
	Example: `  Command:
    //go:generate go run github.com/xoe-labs/ddd-gen domain entity --type YOURTYPE

  Code:
    type Account struct {
        uuid    string ` + "`" + `entity:"required,field uuid is empty;equal,reflect"` + "`" + `
        holder  string ` + "`" + `entity:"setter;getter;stringer"` + "`" + `
        balance int64  ` + "`" + `entity:"private;equal;getter"` + "`" + `
    }

    Important: expects non-pointer type fields.
    Reason: pointers can inadvertedly corrupt your domain.
    Example: a caller can mutate the value.
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return gen_domain.GenEntity(sourceType, validatorMethod)
	},
}

func init() {
	domainCmd.AddCommand(domainEntityCmd)
	domainEntityCmd.Flags().StringVarP(&validatorMethod, "validator", "v", "", "The validator method that constructors should reach out to")
}
