package authorizable

import (
	"github.com/xoe-labs/ddd-gen/internal/test-svc/app"
)

// Actor represents a target entity    --- this message component probably should be autogenerated, eg. by protobuf
type Actor struct {
	user           string
	elevationToken string
}

func (a *Actor) User() string {
	return a.user
}

func (a *Actor) ElevationToken() string {
	return a.elevationToken
}

var (
	_ app.OffersAuthorizable = (*Actor)(nil)
)
